name: CI/CD Sound-Compass

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./sound-compass

jobs:
  build:
      runs-on : self-hosted
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Check rebase
          run: bash ../check_ci.sh
          env:
            COMMIT_SHA: ${{ github.sha }}
        - uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'
            cache-dependency-path: sound-compass/package-lock.json
        - name: Install dependencies
          run: npm ci
        - name: Create environment file
          run: bash ../environment_file.sh
          env:
            SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        - name: Check format
          run: npx prettier --check .
        - name: Check lint
          run: ng lint
        - name: Build the application
          run: npm run build